### ISSUE TITLE
Causing interface crash

### ISSUE THREAD

**Issue by greerga** [Athou/ItemLinkLevel#1]
On high-population realms with a lot of items having sockets linked in trade chat, the function "ItemHasSockets" creates a lot of frames and appears to eventually exceed some limit on the number of frames as the entire interface crashes as if pressing Alt+Z but can't be undone without /reload or /logout.

If the function instead reuses the frame, like "tooltip" behaves, then the interface crash is avoided.

**Comment by Athou** [comment]
Good catch, thanks. I'll fix it tonight !

**Comment by Athou** [comment]
Should be fixed now! Thanks for the report :+1:
