### ISSUE TITLE
New bug (can't tell when it occured unfortunately)

### ISSUE THREAD

**Issue by sthdevilish** [Athou/ItemLinkLevel#6]
1x ItemLinkLevelTooltipMoneyFrame1:SetPoint(): Couldn't find region named 'ItemLinkLevelTooltipTextLeft8'
[string "=[C]"]: in function `SetPoint'
[string "@Interface/FrameXML/GameTooltip.lua"]:355: in function `SetTooltipMoney'
[string "@Interface/FrameXML/GameTooltip.lua"]:317: in function <Interface/FrameXML/GameTooltip.lua:315>
[string "=[C]"]: in function `SetHyperlink'
[string "@Interface/AddOns/ItemLinkLevel/main.lua"]:80: in function <Interface/AddOns/ItemLinkLevel/main.lua:74>
[string "@Interface/AddOns/ItemLinkLevel/main.lua"]:130: in function `filterFunc'
[string "@Interface/FrameXML/ChatFrame.lua"]:3586: in function `ChatFrame_MessageEventHandler'
[string "@Interface/FrameXML/ChatFrame.lua"]:3145: in function `ChatFrame_OnEvent'
[string "*FloatingChatFrame.xml:525_OnEvent"]:1: in function <[string "*FloatingChatFrame.xml:525_OnEvent"]:1>

Locals:
(*temporary) = ItemLinkLevelTooltipMoneyFrame1 {
 GoldButton = ItemLinkLevelTooltipMoneyFrame1GoldButton {
 }
 PrefixText = ItemLinkLevelTooltipMoneyFrame1PrefixText {
 }
 trialErrorButton = ItemLinkLevelTooltipMoneyFrame1TrialErrorButton {
 }
 CopperButton = ItemLinkLevelTooltipMoneyFrame1CopperButton {
 }
 moneyType = "STATIC"
 info = <table> {
 }
 0 = <userdata>
 small = 1
 SilverButton = ItemLinkLevelTooltipMoneyFrame1SilverButton {
 }
 SuffixText = ItemLinkLevelTooltipMoneyFrame1SuffixText {
 }
}
(*temporary) = "LEFT"
(*temporary) = "ItemLinkLevelTooltipTextLeft8"
(*temporary) = "LEFT"
(*temporary) = 4
(*temporary) = 0

**Comment by Athou** [comment]
Someone reported this issue on curseforge and I commited a change here, but I haven't release a new version on curseforge yet. Does it still happen with the latest version of this repo?

**Comment by Athou** [comment]
Should be fixed with 2.2.1

**Comment by sthdevilish** [comment]
I will test it out, thank you. I tried downloading files from here few days ago, but it caused many errors (dunno, maybe I did something wrong, not very familiar with github yet either).
